// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function LoadZakaz(arg1) {
  return window['go']['main']['App']['LoadZakaz'](arg1);
}

export function OfficesList(arg1) {
  return window['go']['main']['App']['OfficesList'](arg1);
}

export function Printm(arg1) {
  return window['go']['main']['App']['Printm'](arg1);
}
