// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function Greet(arg1:string):Promise<Array<main.CityAutocomplete>>;

export function OfficesList(arg1:string):Promise<Array<main.Deliverypoints>>;

export function Printm(arg1:main.Deliverypoints):Promise<void>;

export function Prints(arg1:number):Promise<any>;
